cluster.name: opensearch-cluster
network.host: 0.0.0.0
discovery.type: single-node
bootstrap.memory_lock: true

# Tắt SSL hoàn toàn để chạy ở dev/demo
plugins.security.ssl.http.enabled: false
plugins.security.ssl.transport.enabled: false
plugins.security.disabled: true
